# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Promised Land' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database'
  pod 'Localize-Swift', '= 2.0'

  # Pods for Promised Land

  target 'Promised LandTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Promised LandUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
